# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/aa1ab4e8-e680-4a8b-bb64-abc7c25d558b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/97FD-3E56";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # UGREEN NAS SMB/CIFS network mount
  # IMPORTANT: Replace "personal_folder" with your actual share name if different
  # To find available shares, run: nix-shell -p samba --run "smbclient -L //192.168.178.144 -U username"
  # Common UGREEN NAS share names: "Public", "personal_folder", "media", etc.
  fileSystems."/mnt/ugreen-nas" = {
    device = "//192.168.178.144/personal_folder";
    fsType = "cifs";
    options = [
      # Authentication
      "credentials=/root/.secrets/samba-credentials"
      "sec=ntlmssp" # Use NTLMv2 authentication

      # User/Group mapping - adjust UID/GID to match your user
      "uid=1000"
      "gid=100"

      # File and directory permissions
      "file_mode=0755"
      "dir_mode=0755"

      # Network and reliability options
      "x-systemd.automount" # Automount on access
      "x-systemd.idle-timeout=300" # Unmount after 5 minutes of inactivity
      "x-systemd.mount-timeout=30" # Timeout for mount attempts
      "x-systemd.requires=network-online.target" # Wait for network
      "noauto" # Don't mount at boot, use automount instead

      # Performance and compatibility
      "vers=3.0" # SMB protocol version (3.0, supports 2.0, 2.1, 3.0)
      "cache=loose" # Better performance, less strict consistency
      "rsize=130048" # Read buffer size (128KB)
      "wsize=130048" # Write buffer size (128KB)

      # Reliability options
      "_netdev" # Network device, don't mount until network is up
      "nofail" # Don't fail boot if mount fails
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/4c410f48-47bb-4b37-914a-489cf4ad28c6"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
