#!/usr/bin/env bash
# NixOS External Secrets Setup Script
# ====================================
# This script helps set up the external secrets files on your NAS
# Run it once to create the initial secret files, then fill in the values
#
# Usage: ./scripts/setup-secrets.sh [SECRETS_DIR]
#   SECRETS_DIR defaults to: /mnt/ugreen-nas/Coding/SecretsBackup2025/.secrets

set -euo pipefail

# Configuration
SECRETS_DIR="${1:-/mnt/ugreen-nas/Coding/SecretsBackup2025/.secrets}"
SSH_DIR="$(dirname "$SECRETS_DIR")/.ssh"
GNUPG_DIR="$(dirname "$SECRETS_DIR")/.gnupg"
GH_CONFIG_DIR="$(dirname "$SECRETS_DIR")/.config/gh"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

echo "========================================"
echo "NixOS External Secrets Setup"
echo "========================================"
echo ""
echo "This script will create the following structure:"
echo "  $SECRETS_DIR/"
echo "    user-password-hash   - Hashed user password"
echo "    samba-credentials    - Samba/CIFS credentials"
echo "    env-secrets.sh       - Environment variables (API keys)"
echo "  $SSH_DIR/               - SSH keys"
echo "  $GNUPG_DIR/             - GPG keyring"
echo "  $GH_CONFIG_DIR/         - GitHub CLI config"
echo ""

# Check if NAS is accessible
if [[ ! -d "$(dirname "$SECRETS_DIR")" ]]; then
  error "Parent directory not found: $(dirname "$SECRETS_DIR")"
  error "Please ensure the NAS is mounted at /mnt/ugreen-nas"
  exit 1
fi

# Create directories
info "Creating directories..."
mkdir -p "$SECRETS_DIR"
mkdir -p "$SSH_DIR"
mkdir -p "$GNUPG_DIR"
mkdir -p "$GH_CONFIG_DIR"
chmod 700 "$SECRETS_DIR" "$SSH_DIR" "$GNUPG_DIR" "$GH_CONFIG_DIR"

# Create user-password-hash if not exists
PASSWORD_FILE="$SECRETS_DIR/user-password-hash"
if [[ ! -f "$PASSWORD_FILE" ]]; then
  info "Creating user password hash file..."
  echo ""
  echo "Enter the user password (will be hashed with SHA-512):"
  read -s -p "Password: " USER_PASSWORD
  echo ""

  if command -v mkpasswd &>/dev/null; then
    echo "$USER_PASSWORD" | mkpasswd -m sha-512 -s >"$PASSWORD_FILE"
  elif command -v openssl &>/dev/null; then
    # Fallback to openssl
    SALT=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
    echo -n "$USER_PASSWORD" | openssl passwd -6 -stdin -salt "$SALT" >"$PASSWORD_FILE"
  else
    error "Neither mkpasswd nor openssl found. Please install one of them."
    exit 1
  fi
  chmod 600 "$PASSWORD_FILE"
  info "Password hash saved to: $PASSWORD_FILE"
else
  info "Password file already exists: $PASSWORD_FILE"
fi

# Create samba-credentials if not exists
SAMBA_FILE="$SECRETS_DIR/samba-credentials"
if [[ ! -f "$SAMBA_FILE" ]]; then
  info "Creating samba credentials file..."
  echo ""
  read -p "Samba username [moshpithome]: " SAMBA_USER
  SAMBA_USER="${SAMBA_USER:-moshpithome}"

  read -s -p "Samba password: " SAMBA_PASS
  echo ""

  read -p "Samba domain [WORKGROUP]: " SAMBA_DOMAIN
  SAMBA_DOMAIN="${SAMBA_DOMAIN:-WORKGROUP}"

  cat >"$SAMBA_FILE" <<EOF
username=$SAMBA_USER
password=$SAMBA_PASS
domain=$SAMBA_DOMAIN
EOF
  chmod 600 "$SAMBA_FILE"
  info "Samba credentials saved to: $SAMBA_FILE"
else
  info "Samba credentials file already exists: $SAMBA_FILE"
fi

# Create env-secrets.sh if not exists
ENV_FILE="$SECRETS_DIR/env-secrets.sh"
if [[ ! -f "$ENV_FILE" ]]; then
  info "Creating environment secrets file..."
  echo ""

  read -p "Anthropic API key (or press Enter to skip): " ANTHROPIC_KEY
  read -p "OpenAI API key (or press Enter to skip): " OPENAI_KEY
  read -p "GitHub token (or press Enter to skip): " GITHUB_TOKEN
  read -p "OpenRouter API key (or press Enter to skip): " OPENROUTER_KEY

  cat >"$ENV_FILE" <<'HEADER'
#!/usr/bin/env bash
# Environment secrets for NixOS
# This file is sourced in shell sessions to provide API keys and tokens
# Generated by setup-secrets.sh

HEADER

  [[ -n "$ANTHROPIC_KEY" ]] && echo "export ANTHROPIC_API_KEY=\"$ANTHROPIC_KEY\"" >>"$ENV_FILE"
  [[ -n "$OPENAI_KEY" ]] && echo "export OPENAI_API_KEY=\"$OPENAI_KEY\"" >>"$ENV_FILE"
  [[ -n "$GITHUB_TOKEN" ]] && echo "export GITHUB_TOKEN=\"$GITHUB_TOKEN\"" >>"$ENV_FILE"
  [[ -n "$OPENROUTER_KEY" ]] && echo "export OPENROUTER_API_KEY=\"$OPENROUTER_KEY\"" >>"$ENV_FILE"

  chmod 600 "$ENV_FILE"
  info "Environment secrets saved to: $ENV_FILE"
else
  info "Environment secrets file already exists: $ENV_FILE"
fi

# Copy existing SSH keys if they exist locally
if [[ -d "$HOME/.ssh" ]] && [[ ! "$(ls -A "$SSH_DIR" 2>/dev/null)" ]]; then
  echo ""
  read -p "Copy existing SSH keys from ~/.ssh to NAS? [y/N]: " COPY_SSH
  if [[ "$COPY_SSH" =~ ^[Yy]$ ]]; then
    cp -r "$HOME/.ssh"/* "$SSH_DIR"/ 2>/dev/null || true
    chmod 700 "$SSH_DIR"
    chmod 600 "$SSH_DIR"/* 2>/dev/null || true
    chmod 644 "$SSH_DIR"/*.pub 2>/dev/null || true
    info "SSH keys copied to: $SSH_DIR"
  fi
fi

# Copy existing GPG keyring if it exists locally
if [[ -d "$HOME/.gnupg" ]] && [[ ! "$(ls -A "$GNUPG_DIR" 2>/dev/null)" ]]; then
  echo ""
  read -p "Copy existing GPG keyring from ~/.gnupg to NAS? [y/N]: " COPY_GPG
  if [[ "$COPY_GPG" =~ ^[Yy]$ ]]; then
    rsync -a --exclude='*.lock' --exclude='S.*' "$HOME/.gnupg"/ "$GNUPG_DIR"/
    chmod 700 "$GNUPG_DIR"
    chmod 600 "$GNUPG_DIR"/private-keys-v1.d/* 2>/dev/null || true
    info "GPG keyring copied to: $GNUPG_DIR"
  fi
fi

# Copy existing GitHub CLI config if it exists
if [[ -d "$HOME/.config/gh" ]] && [[ ! "$(ls -A "$GH_CONFIG_DIR" 2>/dev/null)" ]]; then
  echo ""
  read -p "Copy existing GitHub CLI config from ~/.config/gh to NAS? [y/N]: " COPY_GH
  if [[ "$COPY_GH" =~ ^[Yy]$ ]]; then
    cp -r "$HOME/.config/gh"/* "$GH_CONFIG_DIR"/ 2>/dev/null || true
    chmod 700 "$GH_CONFIG_DIR"
    chmod 600 "$GH_CONFIG_DIR"/* 2>/dev/null || true
    info "GitHub CLI config copied to: $GH_CONFIG_DIR"
  fi
fi

echo ""
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo ""
info "Your config.nix should have these paths:"
echo ""
cat <<EOF
external = {
  secretsDir = "$SECRETS_DIR";
  userPasswordFile = "$SECRETS_DIR/user-password-hash";
  sambaCredentials = "$SECRETS_DIR/samba-credentials";
  envSecrets = "$SECRETS_DIR/env-secrets.sh";
  sshKeysDir = "$SSH_DIR";
  gpgDir = "$GNUPG_DIR";
  ghConfigDir = "$GH_CONFIG_DIR";
};
EOF
echo ""
warn "Remember: These files contain sensitive data!"
warn "Ensure NAS has proper access controls."
