name: Update Flake

on:
  schedule:
    - cron: '0 0 * * SUN'  # Weekly on Sunday at midnight UTC
  workflow_dispatch:       # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v13
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Update flake inputs
      run: |
        nix flake update --commit-lock-file

    - name: Test build desktop configuration
      run: |
        echo "Testing desktop build with updated inputs"
        nix build .#nixosConfigurations.desktop.config.system.build.toplevel --print-build-logs

    - name: Test build laptop configuration
      run: |
        echo "Testing laptop build with updated inputs"
        nix build .#nixosConfigurations.laptop.config.system.build.toplevel --print-build-logs

    - name: Check flake after update
      run: nix flake check --print-build-logs

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update flake inputs'
        title: 'chore: update flake inputs'
        body: |
          ## Automated Flake Update

          This PR updates all flake inputs to their latest versions.

          ### Changes
          - Updated all flake inputs via `nix flake update`
          - Verified both desktop and laptop configurations build successfully
          - Passed flake check validation

          ### Testing
          - [x] Desktop configuration builds
          - [x] Laptop configuration builds
          - [x] Flake check passes

          Generated by GitHub Actions workflow.
        branch: update-flake-inputs
        delete-branch: true
